### ISSUE TITLE
Is creates gulpfile.tmp.1488792680004.js which ...

### ISSUE THREAD

**Issue by blaasvaer** [robatron/gulp-chug#23]
... exits with an error. What's going on with that?

**Comment by robatron** [comment]
If the target gulpfile(s) are a buffer, i.e., if `{ read: false }` is not specified, a temp file will be created from the buffer then executed:

https://github.com/robatron/gulp-chug/blob/master/index.js#L83

If the temp file exists with an error, there is most likely a problem with the target gulpfile(s). If you don't need to manipulate the target gulpfile(s)' buffer before execution, consider using the `{ read: false }` option to execute the target gulpfile(s) directly:

https://github.com/robatron/gulp-chug#make-gulp-chug-faster-by-ignoring-file-contents
